/** A habit the user wants to track, as stored in the `habits` table. */
export interface Habit {
  id: HabitId;
  name: string;
  /** Optional emoji/glyph. Reserved for a later phase; the grid does not render it. */
  icon: string | null;
  /** `false` hides the habit from the grid without deleting its history. */
  active: boolean;
  sortOrder: number;
  /**
   * When the habit was created, as a local `YYYY-MM-DD` key. This is the start
   * of the window the analysis scores the habit over, so a habit added last
   * week is not marked down for the months before it existed.
   */
  createdAt: DateKey;
}

/** A `habits.id` — a UUID generated by PostgreSQL. */
export type HabitId = string;

/** A calendar date in local time, formatted as `YYYY-MM-DD`. */
export type DateKey = string;

/** One row of the `habit_logs` table: a habit's state on a single date. */
export interface HabitLog {
  id: string;
  habitId: HabitId;
  date: DateKey;
  completed: boolean;
}

/** A year/month pair. `month` is 0-indexed, matching the JavaScript `Date` API. */
export interface Month {
  year: number;
  month: number;
}

/** One column of the tracker grid. */
export interface CalendarDay {
  date: Date;
  key: DateKey;
  dayOfMonth: number;
  /** Short weekday label, e.g. `Fri`. */
  weekdayLabel: string;
  /** `true` on a Sunday, the one day of the week nothing is expected. */
  isRestDay: boolean;
  isToday: boolean;
}

/**
 * Completed habits, grouped by date. Only completions are held in memory: a
 * habit that is absent for a date is simply not done. `habit_logs` rows with
 * `completed = false` are therefore dropped when the map is built.
 */
export type CompletionMap = Record<DateKey, Record<HabitId, true> | undefined>;

/** One row of the `daily_tasks` table: something to do on a specific date. */
export interface DailyTask {
  id: string;
  date: DateKey;
  title: string;
  /** Free-text detail. Empty when the task is just a one-liner. */
  description: string;
  completed: boolean;
  sortOrder: number;
}
